// Blog posts. Body blocks: { h2 } | { p } | { ul: [] } | { ol: [] } | { quote }.
// Draft articles written for launch — review before publishing, or swap this file for a CMS.

const AUTHOR = { name: 'Innovage Team', role: 'Strategy, Design & Engineering' };

const raw = [
  {
    slug: 'custom-software-vs-off-the-shelf',
    category: 'Strategy',
    date: '2026-09-18',
    title: 'Custom Software vs. Off-the-Shelf: How to Decide',
    excerpt: 'When does it make sense to build your own platform? A practical framework for weighing cost, flexibility and long-term value.',
    body: [
      { p: 'Every growing business eventually hits the same fork in the road. The tools that got you here — a CRM, a spreadsheet, a handful of SaaS subscriptions — start to strain. Do you buy another product, or build something that fits the way you actually work?' },
      { p: 'There is no universally right answer. But there is a reliable way to make the decision, and it starts with being honest about where your business is genuinely different.' },
      { h2: 'Start with the process, not the product' },
      { p: 'Before comparing vendors or estimating development costs, map the workflow you are trying to support. Who touches it, what information moves between steps, and where does it currently break down? Off-the-shelf software is built around the average company in a category. If your process is close to average, buying is usually faster and cheaper.' },
      { p: 'If the process is where you win customers — a faster quote, a smoother onboarding, a service model competitors cannot copy — forcing it into a generic tool means giving up the very thing that sets you apart.' },
      { h2: 'When off-the-shelf is the right call' },
      { ul: [
        'The workflow is standard for your industry (accounting, payroll, email marketing).',
        'You need something working this month, not this quarter.',
        'The product covers 80% or more of your requirements without heavy workarounds.',
        'Total subscription cost stays reasonable as your team and usage grow.',
      ] },
      { h2: 'When custom software pays for itself' },
      { ul: [
        'Your team spends hours each week bridging gaps between tools with copy-paste and spreadsheets.',
        'Per-seat or per-transaction pricing is climbing faster than revenue.',
        'You need to own your data, integrations or customer experience end to end.',
        'The process is a competitive advantage and changes as you learn.',
      ] },
      { h2: 'Look at five-year cost, not launch cost' },
      { p: 'Subscriptions look cheap on day one and expensive in year four. Custom builds look expensive on day one and often cheaper over the life of the system. Compare total cost of ownership: licences, workarounds, integration upkeep, staff time and the cost of switching later.' },
      { quote: 'The most expensive software is the kind your team has to work around every single day.' },
      { h2: 'The hybrid route most businesses take' },
      { p: 'In practice the answer is rarely all-or-nothing. Many of our clients keep proven products for commodity functions and build a custom layer — a portal, a dashboard, an automation hub — that ties everything together around their unique process.' },
      { p: 'If you are weighing the decision, start with a short discovery session. An hour spent mapping the workflow usually makes the right answer obvious.' },
    ],
  },
  {
    slug: 'automate-before-you-hire',
    category: 'Automation',
    date: '2026-08-27',
    title: 'Automate Before You Hire: Finding Hidden Hours',
    excerpt: 'Spreadsheets, copy-paste and email approvals quietly eat your week. Here is how to spot and remove them.',
    body: [
      { p: 'When a team feels stretched, the instinct is to hire. Sometimes that is right. But in many businesses a surprising share of every week goes to work no person should be doing: retyping data, chasing approvals, building the same report every Monday.' },
      { p: 'Before adding headcount, it is worth finding those hidden hours. Automation is often cheaper than a new role — and it makes every future hire more productive.' },
      { h2: 'Signs your team is doing robot work' },
      { ul: [
        'The same information is typed into more than one system.',
        'Approvals live in email threads and someone has to chase them.',
        'Reports are rebuilt manually from exports every week or month.',
        'Customers wait on updates that are really just status changes.',
        'Spreadsheets are the "source of truth" and only one person understands them.',
      ] },
      { h2: 'Run a one-week time audit' },
      { p: 'Ask each team member to note repetitive tasks for one week: what they did, how long it took and how often it repeats. Do not judge the tasks yet — just collect them. Most teams are surprised by the total.' },
      { h2: 'Score each task for automation' },
      { ol: [
        'Frequency — how often does it happen?',
        'Time — how long does each instance take?',
        'Rules — is the decision logic clear and repeatable?',
        'Risk — what does an error cost today?',
      ] },
      { p: 'High-frequency, rule-based tasks with a real cost of error are your best candidates. Judgement-heavy work usually is not — keep people there.' },
      { h2: 'Start small, then connect' },
      { p: 'The best automation projects begin with one painful workflow and a measurable goal: hours saved, errors avoided, response time reduced. Once that works, connect the next system. Over a few months, isolated tools become a joined-up operation.' },
      { quote: 'Automation should give people their time back for the work only people can do.' },
      { h2: 'What it looks like in practice' },
      { p: 'Typical early wins include syncing orders between a store and an accounting system, routing form submissions to the right person automatically, generating recurring reports and sending customers proactive status updates. Each one is small. Together they often add up to a full role’s worth of time.' },
    ],
  },
  {
    slug: 'website-that-converts',
    category: 'Design',
    date: '2026-08-04',
    title: 'What Makes a Website Actually Convert',
    excerpt: 'Beyond good looks: the structure, speed and messaging patterns behind sites that turn visitors into customers.',
    body: [
      { p: 'A beautiful website that does not generate enquiries is an expensive brochure. Conversion is not about tricks or pop-ups — it comes from clarity, speed and trust, designed in from the first wireframe.' },
      { h2: 'Clarity in the first five seconds' },
      { p: 'Visitors decide quickly whether they are in the right place. Your first screen should answer three questions without scrolling: what you do, who it is for and what to do next. Clever headlines that need decoding cost you attention you cannot afford.' },
      { h2: 'One primary action per page' },
      { p: 'Every page should have a single most-important action — book a call, request a quote, start a trial. Secondary links are fine, but the primary action should be visually obvious and repeated at natural decision points.' },
      { h2: 'Speed is a design decision' },
      { ul: [
        'Compress and correctly size every image; use modern formats.',
        'Load animation and heavy scripts only where they add real value.',
        'Keep the critical content visible before third-party scripts load.',
        'Test on a mid-range phone over a normal connection, not just your office Wi-Fi.',
      ] },
      { p: 'Every second of delay quietly erodes conversions, especially on mobile where most first visits happen.' },
      { h2: 'Proof beats promises' },
      { p: 'Visitors trust what others say about you more than what you say about yourself. Place evidence close to your claims: client logos near the hero, a short case study beside a service description, real numbers instead of adjectives.' },
      { quote: 'Show the outcome, not just the feature.' },
      { h2: 'Reduce friction in forms' },
      { p: 'Ask only for what you need to start the conversation. Every extra field loses a percentage of people. Use clear labels, helpful error messages and tell people what happens after they submit.' },
      { h2: 'Measure, then iterate' },
      { p: 'Conversion design is never finished. Track where visitors drop off, test one change at a time and keep what works. Small, steady improvements compound into a site that keeps getting better at its job.' },
    ],
  },
  {
    slug: 'saas-mvp-roadmap',
    category: 'SaaS',
    date: '2026-07-15',
    title: 'From Idea to SaaS MVP in Seven Steps',
    excerpt: 'Our Discover-to-Evolve process applied to launching a subscription product without over-building.',
    body: [
      { p: 'Most SaaS products that struggle do not fail because of bad code. They fail because they took too long to reach real users, or launched with features nobody asked for. A focused MVP fixes both problems.' },
      { p: 'Here is how our seven-step process applies to taking a subscription product from idea to launch.' },
      { h2: '1. Discover' },
      { p: 'Talk to the people who would pay. Understand the problem, the current workaround and what it costs them. You are looking for pain that is frequent, expensive and poorly served today.' },
      { h2: '2. Define' },
      { p: 'Write down the single job your MVP must do brilliantly. List everything else and move it to "later". Define what success looks like: sign-ups, activation, retention or revenue.' },
      { h2: '3. Design' },
      { p: 'Prototype the core journey before writing production code. Clickable designs let you test with real users in days and fix confusion while it is still cheap.' },
      { h2: '4. Build' },
      { p: 'Build in short phases with something demonstrable at the end of each. Invest early in the foundations that are painful to change later — accounts, roles, billing and data structure — and keep everything else lean.' },
      { h2: '5. Validate' },
      { p: 'Test the full workflow the way customers will use it, including the edge cases: failed payments, invited team members, cancelled plans. A small private beta surfaces problems that internal testing misses.' },
      { h2: '6. Launch' },
      { p: 'Launch to a defined audience with onboarding, support and analytics in place. A quiet launch to the right hundred users teaches more than a loud launch to ten thousand of the wrong ones.' },
      { h2: '7. Evolve' },
      { p: 'Now the real work begins. Watch how people use the product, talk to those who churn and prioritise ruthlessly. The roadmap should be driven by evidence, not by the longest feature request list.' },
      { quote: 'An MVP is not a smaller product. It is the fastest route to learning what the right product is.' },
    ],
  },
  {
    slug: 'maintenance-matters',
    category: 'Support',
    date: '2026-06-30',
    title: 'Why Website Maintenance Is a Growth Lever',
    excerpt: 'Security, speed and continuous improvement: the case for treating your site like a product.',
    body: [
      { p: 'Many businesses treat a website launch as the finish line. In reality it is the starting point. A site that is not maintained slowly becomes slower, less secure and less effective — usually without anyone noticing until something breaks.' },
      { h2: 'Security is not optional' },
      { p: 'Plugins, frameworks and servers receive security updates constantly. Skipping them leaves known vulnerabilities open to automated attacks that scan the web around the clock. Regular updates, monitoring and tested backups are the minimum standard.' },
      { h2: 'Performance drifts over time' },
      { p: 'New content, images, tracking scripts and features add weight. Without periodic tuning, a fast site becomes a slow one, and both search rankings and conversions suffer.' },
      { h2: 'What good maintenance includes' },
      { ul: [
        'Scheduled core, plugin and dependency updates with testing.',
        'Uptime and security monitoring with alerts.',
        'Automated, off-site backups — and regular restore tests.',
        'Performance checks and optimisation.',
        'Small content and design improvements based on analytics.',
      ] },
      { quote: 'Treat your website like a product, not a project.' },
      { h2: 'From maintenance to improvement' },
      { p: 'The real value appears when maintenance includes continuous improvement: refining pages that underperform, testing new calls to action and adapting to how customers behave. Over a year, those small changes often outperform a full redesign.' },
    ],
  },
  {
    slug: 'mobile-app-checklist',
    category: 'Mobile',
    date: '2026-06-09',
    title: 'The Pre-Launch Checklist for Mobile Apps',
    excerpt: 'Everything to validate before you hit submit on the App Store and Google Play.',
    body: [
      { p: 'Launching a mobile app is more involved than publishing a website. Store reviews, device fragmentation and the difficulty of fixing mistakes once users have installed a version all raise the stakes. A disciplined pre-launch checklist saves weeks of pain.' },
      { h2: 'Functionality and stability' },
      { ul: [
        'Core journeys tested end to end on real iOS and Android devices.',
        'Poor network, offline and interrupted-session behaviour handled gracefully.',
        'Crash reporting and analytics installed and verified.',
        'Push notifications tested on both platforms, including permission prompts.',
      ] },
      { h2: 'Performance' },
      { ul: [
        'Cold start time measured on older, lower-end devices.',
        'Images and assets optimised for app size.',
        'Battery and data usage checked during long sessions.',
      ] },
      { h2: 'Store readiness' },
      { ul: [
        'App name, subtitle, description and keywords finalised.',
        'Screenshots and preview video for every required device size.',
        'Privacy policy URL and data-collection disclosures completed accurately.',
        'Demo account credentials prepared for store reviewers.',
      ] },
      { h2: 'Accessibility and polish' },
      { p: 'Check dynamic text sizes, colour contrast and screen-reader labels. Accessibility is increasingly expected by users and reviewers alike, and it makes the app better for everyone.' },
      { quote: 'Users forgive a missing feature far more easily than a crash on first launch.' },
      { h2: 'After you hit submit' },
      { p: 'Plan for the first two weeks: monitor crashes and reviews daily, respond to feedback quickly and have a fast-follow release ready. The launch version is the beginning of the conversation with your users, not the end.' },
    ],
  },
];

const wordsIn = (b) => (b.p || b.h2 || b.quote || [...(b.ul || []), ...(b.ol || [])].join(' ')).split(/\s+/).length;
export const slugify = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

export const posts = raw.map((p) => ({
  ...p,
  author: AUTHOR,
  image: `/images/blog/${p.slug}.webp`,
  read: `${Math.max(3, Math.round(p.body.reduce((n, b) => n + wordsIn(b), 0) / 200))} min`,
}));

export const getPost = (slug) => posts.find((p) => p.slug === slug);

export const formatDate = (d) => new Date(d + 'T12:00:00').toLocaleDateString('en-CA', { year: 'numeric', month: 'long', day: 'numeric' });
